package com.soccerstars.aimassist;
import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;
public class AimOverlay extends View{
 Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);Bitmap frame;ArrayList<PointF> path=new ArrayList<>();PointF end;RectF field=new RectF();long lastUpdate;
 public AimOverlay(Context c){super(c);p.setStrokeCap(Paint.Cap.ROUND);}
 public void setFrame(Bitmap b){if(b==null)return;Bitmap old=frame;frame=b;if(old!=null&&!old.isRecycled())old.recycle();long now=SystemClock.uptimeMillis();if(now-lastUpdate>140){lastUpdate=now;analyze();postInvalidate();}}
 void analyze(){path.clear();end=null;Bitmap b=frame;if(b==null||b.isRecycled())return;int W=b.getWidth(),H=b.getHeight(),step=Math.max(8,Math.min(W,H)/130),minX=W,minY=H,maxX=0,maxY=0,n=0;try{for(int y=H/10;y<H*9/10;y+=step)for(int x=0;x<W;x+=step){int c=b.getPixel(x,y),r=Color.red(c),g=Color.green(c),bl=Color.blue(c);if(g>r*1.08f&&g>bl*1.08f&&g>40){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);n++;}}if(n<60)return;field.set(minX,minY,maxX,maxY);PointF s=findBright(b);if(s==null)return;float dx=field.width()*.22f,dy=-field.height()*.09f,x=s.x,y=s.y;path.add(new PointF(x,y));for(int i=0;i<8;i++){float tx=dx>0?(field.right-x)/dx:(field.left-x)/dx,ty=dy>0?(field.bottom-y)/dy:(field.top-y)/dy,t=Math.min(tx>0?tx:1e9f,ty>0?ty:1e9f);if(t>1e8)break;x+=dx*t;y+=dy*t;path.add(new PointF(x,y));if(tx<ty)dx=-dx;else dy=-dy;x+=dx*.01f;y+=dy*.01f;}if(path.size()>1)end=path.get(path.size()-1);}catch(Throwable ignored){}}
 PointF findBright(Bitmap b){PointF best=null;double score=Double.MAX_VALUE;float cx=field.centerX(),cy=field.bottom-field.height()*.2f;for(int y=(int)field.top;y<field.bottom;y+=8)for(int x=(int)field.left;x<field.right;x+=8){int c=b.getPixel(x,y);if(Color.red(c)>185&&Color.green(c)>185&&Color.blue(c)>185){double s=Math.hypot(x-cx,(y-cy)*.7);if(s<score){score=s;best=new PointF(x,y);}}}return best;}
 protected void onDraw(Canvas c){super.onDraw(c);if(path.size()<2)return;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(Color.CYAN);for(int i=1;i<path.size();i++)c.drawLine(path.get(i-1).x,path.get(i-1).y,path.get(i).x,path.get(i).y,p);if(end!=null){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(200,255,70,70));c.drawCircle(end.x,end.y,18,p);p.setStyle(Paint.Style.STROKE);p.setColor(Color.WHITE);c.drawCircle(end.x,end.y,25,p);}}
}