package com.soccerstars.aimassist;
import android.app.*; import android.content.*; import android.graphics.PixelFormat; import android.hardware.display.*; import android.media.*; import android.media.projection.*; import android.os.*; import android.util.DisplayMetrics; import android.view.WindowManager;
public class CaptureService extends Service {
 static final String CH="ssaa"; MediaProjection projection; VirtualDisplay display; ImageReader reader; HandlerThread thread; Handler worker; AimOverlay overlay; long last;
 public void onCreate(){super.onCreate();thread=new HandlerThread("SSAA");thread.start();worker=new Handler(thread.getLooper());if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CH,"Soccer Stars Aim Assist",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 Notification note(){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CH):new Notification.Builder(this);return b.setContentTitle("Soccer Stars Aim Assist").setContentText("پایش فعال است").setSmallIcon(R.drawable.ic_launcher).setOngoing(true).build();}
 public int onStartCommand(Intent i,int f,int id){try{startForeground(7,note());int rc=i.getIntExtra("resultCode",RESULT_CANCELED);Intent d=Build.VERSION.SDK_INT>=33?i.getParcelableExtra("projectionData",Intent.class):i.getParcelableExtra("projectionData");if(d==null)return START_NOT_STICKY;MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(rc,d);if(projection==null)return START_NOT_STICKY;DisplayMetrics dm=getResources().getDisplayMetrics();int w=Math.min(dm.widthPixels,720),h=Math.max(1,dm.heightPixels*w/Math.max(1,dm.widthPixels));reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(this::frame,worker);display=projection.createVirtualDisplay("SSAA",w,h,dm.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,worker);new Handler(Looper.getMainLooper()).post(this::add);return START_NOT_STICKY;}catch(Throwable e){stopSelf();return START_NOT_STICKY;}}
 void add(){try{if(overlay!=null)return;overlay=new AimOverlay(this);WindowManager w=(WindowManager)getSystemService(WINDOW_SERVICE);int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,-1,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);w.addView(overlay,p);}catch(Throwable ignored){}}
 void frame(ImageReader r){long n=SystemClock.uptimeMillis();if(n-last<180)return;last=n;Image im=null;try{im=r.acquireLatestImage();if(im!=null&&overlay!=null)overlay.postInvalidate();}catch(Throwable ignored){}finally{if(im!=null)im.close();}}
 public void onDestroy(){try{if(display!=null)display.release();}catch(Throwable ignored){}try{if(reader!=null)reader.close();}catch(Throwable ignored){}try{if(projection!=null)projection.stop();}catch(Throwable ignored){}try{if(overlay!=null)((WindowManager)getSystemService(WINDOW_SERVICE)).removeView(overlay);}catch(Throwable ignored){}if(thread!=null)thread.quitSafely();super.onDestroy();}
 public IBinder onBind(Intent i){return null;}
}
