package com.soccerstars.aimassist;
import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.util.DisplayMetrics;import android.view.*;
public class CaptureService extends Service{
 MediaProjection mp;ImageReader reader;HandlerThread ht;Handler handler;AimOverlay overlay;long lastFrame=0;int width,height;
 public void onCreate(){super.onCreate();ht=new HandlerThread("SSAA-Capture");ht.start();handler=new Handler(ht.getLooper());if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel("ssaa","Aim Assist",NotificationManager.IMPORTANCE_LOW);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}
 public int onStartCommand(Intent in,int flags,int id){try{int code=in.getIntExtra("code",0);Intent data=in.getParcelableExtra("data");startForeground(42,makeNotification());MediaProjectionManager mm=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);mp=mm.getMediaProjection(code,data);DisplayMetrics d=getResources().getDisplayMetrics();width=d.widthPixels;height=d.heightPixels;int capW=Math.min(width,1280),capH=Math.max(1,(int)((long)height*capW/Math.max(1,width)));reader=ImageReader.newInstance(capW,capH,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(x->frame(x,capW,capH),handler);mp.createVirtualDisplay("SSAA",capW,capH,(int)d.density,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,handler);new Handler(Looper.getMainLooper()).post(this::showOverlay);return START_STICKY;}catch(Exception e){stopSelf();return START_NOT_STICKY;}}
 Notification makeNotification(){Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,"ssaa"):new Notification.Builder(this);return b.setContentTitle("Soccer Stars Aim Assist").setContentText("در حال تحلیل صفحه").setSmallIcon(R.drawable.ic_launcher).build();}
 void frame(ImageReader ir,int w,int h){long now=SystemClock.uptimeMillis();Image im=null;if(now-lastFrame<140)return;lastFrame=now;try{im=ir.acquireLatestImage();if(im==null||overlay==null)return;Image.Plane pl=im.getPlanes()[0];Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);pl.getBuffer().rewind();b.copyPixelsFromBuffer(pl.getBuffer());overlay.setFrame(b);}catch(Throwable ignored){}finally{if(im!=null)im.close();}}
 void showOverlay(){try{overlay=new AimOverlay(this);WindowManager wm=(WindowManager)getSystemService(WINDOW_SERVICE);int type=Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;WindowManager.LayoutParams lp=new WindowManager.LayoutParams(-1,-1,type,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);wm.addView(overlay,lp);}catch(Exception e){stopSelf();}}
 public void onDestroy(){try{if(reader!=null)reader.close();}catch(Exception ignored){}try{if(mp!=null)mp.stop();}catch(Exception ignored){}try{if(overlay!=null)((WindowManager)getSystemService(WINDOW_SERVICE)).removeView(overlay);}catch(Exception ignored){}if(ht!=null)ht.quitSafely();super.onDestroy();}
 public IBinder onBind(Intent i){return null;}
}